plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.91'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client_1')
            jvmArgument '-XX:+AllowEnhancedClassRedefinition'
            jvmArgument '-Xmx4g'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        client2 {
            client()
            gameDirectory = project.file('run/client_2')
            programArgument '--username'
            programArgument 'Ranpoes'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            gameDirectory = project.file('run/server')
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            gameDirectory = project.file('run-data')
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenCentral()
    flatDir {
        dir 'libs'
    }
    maven {
        url = 'https://repo.spongepowered.org/repository/maven-public/'
    }
    maven {
        url 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    maven {
        url = 'https://api.modrinth.com/maven'
    }
    maven {
        url = 'https://jitpack.io'
        content {
            includeGroup 'com.github.mcmodderanchor'
        }
    }
    maven {
        url = 'https://maven.sighs.cc/repository/maven-public/'
    }
    maven {
        name = "Jared's maven"
        url = 'https://maven.blamejared.com/'
    }
    maven {
        name = 'Mod Maven'
        url = 'https://modmaven.k-4u.nl'
    }
    maven {
        name = 'Valkyrien Skies'
        url = 'https://maven.valkyrienskies.org'
    }
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }
    mavenLocal()
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

dependencies {
    // JS支持
    jarJar(implementation('org.ywzj:rhino:1.8.1')) {
        version {
            strictly '[1.8.1,)'
            prefer '1.8.1'
        }
    }
    additionalRuntimeClasspath 'org.ywzj:rhino:1.8.1'
    // SBM
    jarJar(modImplementation('com.github.mcmodderanchor:simplebedrockmodel:2.5.1-forge-mc1.20.1')) {
        version {
            strictly '[2.5.1-forge-mc1.20.1,)'
            prefer '2.5.1-forge-mc1.20.1'
        }
    }
    compileOnly('com.maydaymemory:mae:1.1.2') {
        exclude group: 'com.google.code.findbugs', module: 'jsr305'
        exclude group: 'it.unimi.dsi', module: 'fastutil'
        exclude group: 'org.joml', module: 'joml'
    }
    // mixinextras
    compileOnly annotationProcessor('io.github.llamalad7:mixinextras-common:0.3.6')
    jarJar(modImplementation('io.github.llamalad7:mixinextras-forge:0.3.6')) {
        version {
            strictly '[0.3.6,)'
            prefer '0.3.6'
        }
    }
    // JEI
    modCompileOnly "mezz.jei:jei-1.20.1-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-1.20.1-forge-api:${jei_version}"
    modLocalRuntime 'mezz.jei:jei-1.20.1-forge:15.20.0.104'
    // 各类模组的兼容性测试
    modLocalRuntime 'curse.maven:configured-457570:5180900'
    modLocalRuntime 'curse.maven:spark-361579:4738952'
    // ar
    modLocalRuntime 'curse.maven:accelerated-rendering-1314021:8448250'
    // tacz
    modImplementation 'curse.maven:timeless-and-classics-zero-1028108:7401617-sources-7401626'
    // apricityui
    jarJar(modImplementation 'com.sighs:ApricityUI-forge-1.20.1:1.2.3') {
        version {
            strictly '[1.2.3,)'
            prefer '1.2.3'
        }
    }
    // sbw
    modCompileOnly 'curse.maven:superb-warfare-1218165:7292685'
    modCompileOnly 'curse.maven:curios-309927:6418456'
    modCompileOnly 'curse.maven:geckolib-388172:7553267'
    // vs
    compileOnly('org.valkyrienskies.core:api:1.1.0+') {
        exclude group: 'org.joml', module: 'joml'
    }
    modCompileOnly 'curse.maven:valkyrien-skies-258371:7568034'
    modCompileOnly 'curse.maven:eureka-ships-654384:7419758'
    compileOnly 'thedarkcolour:kotlinforforge:4.11.0'
    // create
    modCompileOnly 'curse.maven:create-328085:7178761'

    if (!project.gradle.startParameter.taskNames.any { it.contains('runServer') }) {
        modLocalRuntime 'maven.modrinth:embeddium:0.3.31+mc1.20.1'
        modLocalRuntime 'curse.maven:rubidium-extra-654373:6101745'
        modLocalRuntime 'curse.maven:oculus-581495:6020952'
    }

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    config 'mixins.ywzj_vehicle.json'
    add sourceSets.main, 'ywzj_vehicle.refmap.json'
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : 'mixins.ywzj_vehicle.json'
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
