/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityBar: typeof import('./src/components/layout/ActivityBar.vue')['default']
    BedrockModelViewer: typeof import('./src/components/editors/BedrockModelViewer.vue')['default']
    EditorArea: typeof import('./src/components/layout/EditorArea.vue')['default']
    EditorTabs: typeof import('./src/components/layout/EditorTabs.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FileTree: typeof import('./src/components/layout/FileTree.vue')['default']
    FormFieldRenderer: typeof import('./src/components/editors/FormFieldRenderer.vue')['default']
    ImagePreview: typeof import('./src/components/editors/ImagePreview.vue')['default']
    InspectorPanel: typeof import('./src/components/layout/InspectorPanel.vue')['default']
    JsonFormEditor: typeof import('./src/components/editors/JsonFormEditor.vue')['default']
    MonacoEditor: typeof import('./src/components/editors/MonacoEditor.vue')['default']
    NamespaceIdSelect: typeof import('./src/components/editors/NamespaceIdSelect.vue')['default']
    VehicleDetail: typeof import('./src/components/views/VehicleDetail.vue')['default']
    VehicleExplorer: typeof import('./src/components/views/VehicleExplorer.vue')['default']
  }
}
